substitutions:
  _APP_NAME: hello
  _PIPELINE_NAME: deploy-demo-pipeline
  _POOL_NAME: demo-pool
  _BIN_AUTHZ_ID: projects/cloudy-labz/attestors/sbominator

steps:

  # Build image
  - id: build
    name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
    - -c
    - |-
      docker build --build-arg VERSION=${TAG_NAME} \
        -t "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_APP_NAME}:${COMMIT_SHA}" \
        -t "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_APP_NAME}:${TAG_NAME}" \
        -t "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_APP_NAME}:latest" \
        .
  
  # Publish image, get sha256
  - id: publish
    name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    waitFor: ["build"]
    args:
    - -c
    - |-
      docker push "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_APP_NAME}:${TAG_NAME}"
      docker image inspect "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_APP_NAME}:${TAG_NAME}" \
        --format '{{index .RepoDigests 0}}' > image-digest.txt 
      cat image-digest.txt

  # Generate SBOM (includes vulnerability scan)
  - id: sbom
    name: us-docker.pkg.dev/cloudy-demos/builders/sbom-builder:v0.3.6
    entrypoint: /bin/bash
    waitFor: ["publish"]
    env:
    - PROJECT=$PROJECT_ID
    - KEY=$_KMS_KEY_NAME
    - COMMIT=$COMMIT_SHA
    - VERSION=$TAG_NAME
    - ATTESTOR=$_BIN_AUTHZ_ID # optional - to add binary attestation
    args:
    - -c
    - |
      builder $(/bin/cat image-digest.txt)

  # Create release in Google Cloud Deploy
  - id: release
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: /bin/bash
    waitFor: ["policy"]
    args:
    - -c
    - |
      gcloud deploy releases create rel-${SHORT_SHA} \
      --delivery-pipeline=${_PIPELINE_NAME} \
      --region=${LOCATION} \
      --annotations=commitId=${REVISION_ID} \
      --images=${_APP_NAME}=$(/bin/cat image-digest.txt)

images:
- ${LOCATION}-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_APP_NAME:$TAG_NAME

options:
  requestedVerifyOption: VERIFIED # ensure attestation gen, provenance metadata, for this build
  sourceProvenanceHash: ["SHA256"]
  pool:
    name: 'projects/$PROJECT_ID/locations/$LOCATION/workerPools/$_POOL_NAME'

tags:
- demo